# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91fab1f75fe3438c92781352e36cd5428ade6fa3cb221dbbc7fde9e63605812421841ccba56440de291bac7666d9ca7f45b8d046b8be9840b7ce068896ed54a1

test:
  secret_key_base: de09053cab2deda0579676d02e8b9ceddc7e4ebc4f7b941c2fb0930ab80d6fa4f0cdbb0f62726830e068278b9a64d59425a8ee8dd2461680d966b565cfa91d99

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
